# Default values for healthyplants.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fzampa/healthyplants
  tag: "v0.0.1"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hostName: healthyplants.mylocal